### ISSUE TITLE
Camp Lambda Logo

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-ui#1]
Design a Logo For Camp Lambda. Logo should contain the Lambda Symbol, and perhaps the words "Camp Lambda".

* [ ] Treatments
* [ ] First Draft
* [ ] Logo SVG file
* [ ] Logo Icon File
* [ ] Add Logo to clam-graphql-api and clam-ui Readme.md

Used in #6 Welcome Page

**Comment by eveporcello** [comment]
Contacted Kimmy about this.
